# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "opensuse/Leap-15.4.x86_64"
  config.vm.network "private_network", type: "dhcp"
  config.vm.provider :virtualbox do |vb|
    vb.cpus = 2
    vb.memory = 16384
  end

  config.vm.hostname = "minecraft-server"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provision "shell", path: "bootstrap.sh"
end